# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:

  - task: NodeTool@0
    inputs:
      versionSpec: '11.x'
    displayName: 'Install Node.js'

  - script: |
      yarn
      yarn lint
      yarn test
    displayName: 'Install and test'

  - script: |
      yarn build:site
      docker build -t ianwalter/$(system.teamProject) .
      docker login -u ianwalter -p $(dockerPassword)
      docker push ianwalter/$(system.teamProject)
    displayName: 'Build and push Docker Image'
